# Generated by Django 6.0.1 on 2026-02-03 07:18

import rk_certificate_portal.storage_backend
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(storage=rk_certificate_portal.storage_backend.PublicMediaStorage(), upload_to='certificates/'),
        ),
    ]
